name: Deploy infrastructure

on:
  push:
    branches:
      - feature/terraform-ci/cd
    # paths:
    #   - terraform/**

jobs:
  run:
    name: Deploy Infra
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auth in GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan
        working-directory: ./terraform

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve plan.tfplan
      #   working-directory: ./terraform

      - name: Clean up plan file
        run: rm -f plan.tfplan
        working-directory: ./terraform
